name: Build

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./src

jobs:
  Build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 1

      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4.0.1
            

    - name: Build
      run: sh build.sh

    - name: Push build
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        git commit -m "Build output" -a
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
